// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// OrderBookModel is an autogenerated mock type for the OrderBookModel type
type OrderBookModel struct {
	mock.Mock
}

// Query provides a mock function with given fields: db
func (_m *OrderBookModel) Query(db *sql.DB) error {
	ret := _m.Called(db)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.DB) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
