// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// OrderModel is an autogenerated mock type for the OrderModel type
type OrderModel struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: db
func (_m *OrderModel) CreateOrder(db *sql.DB) error {
	ret := _m.Called(db)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.DB) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderId provides a mock function with given fields:
func (_m *OrderModel) GetOrderId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
